### This is a sample code written by ABOLFAZL RoostaeiParidari.

### The Data comes from: www.simplilearn.com

### contact: roostaeiabolfazl@gmail.com

In [1]:
import numpy as np
import pandas as pd

In [7]:
data_df = pd.read_csv('faa_ai_prelim.csv')
data_df.head()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data_df.shape

(83, 42)

In [9]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              83 non-null     object
 1   ENTRY_DATE           83 non-null     object
 2   EVENT_LCL_DATE       83 non-null     object
 3   EVENT_LCL_TIME       83 non-null     object
 4   LOC_CITY_NAME        83 non-null     object
 5   LOC_STATE_NAME       83 non-null     object
 6   LOC_CNTRY_NAME       2 non-null      object
 7   RMK_TEXT             83 non-null     object
 8   EVENT_TYPE_DESC      83 non-null     object
 9   FSDO_DESC            81 non-null     object
 10  REGIST_NBR           83 non-null     object
 11  FLT_NBR              6 non-null      object
 12  ACFT_OPRTR           7 non-null      object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      79 non-null     object
 15  ACFT_MISSING_FLAG    0 non-null      float64
 16  ACFT_DMG_DESC        82 non-null     object
 17  FLT_ACTIVITY         13 non-null     object
 18  FLT_PHASE            82 non-null     object
 19  FAR_PART             1 non-null      float64
 20  MAX_INJ_LVL          80 non-null     object
 21  FATAL_FLAG           8 non-null      object
 22  FLT_CRW_INJ_NONE     64 non-null     float64
 23  FLT_CRW_INJ_MINOR    6 non-null      float64
 24  FLT_CRW_INJ_SERIOUS  1 non-null      float64
 25  FLT_CRW_INJ_FATAL    8 non-null      float64
 26  FLT_CRW_INJ_UNK      0 non-null      float64
 27  CBN_CRW_INJ_NONE     0 non-null      float64
 28  CBN_CRW_INJ_MINOR    0 non-null      float64
 29  CBN_CRW_INJ_SERIOUS  0 non-null      float64
 30  CBN_CRW_INJ_FATAL    0 non-null      float64
 31  CBN_CRW_INJ_UNK      1 non-null      float64
 32  PAX_INJ_NONE         17 non-null     float64
 33  PAX_INJ_MINOR        1 non-null      float64
 34  PAX_INJ_SERIOUS      3 non-null      float64
 35  PAX_INJ_FATAL        1 non-null      float64
 36  PAX_INJ_UNK          0 non-null      float64
 37  GRND_INJ_NONE        0 non-null      float64
 38  GRND_INJ_MINOR       0 non-null      float64
 39  GRND_INJ_SERIOUS     0 non-null      float64
 40  GRND_INJ_FATAL       0 non-null      float64
 41  GRND_INJ_UNK         1 non-null      float64
dtypes: float64(22), object(20)
memory usage: 27.4+ KB

In [10]:
data_df.describe()

,ACFT_MISSING_FLAG,FAR_PART,FLT_CRW_INJ_NONE,FLT_CRW_INJ_MINOR,FLT_CRW_INJ_SERIOUS,FLT_CRW_INJ_FATAL,FLT_CRW_INJ_UNK,CBN_CRW_INJ_NONE,CBN_CRW_INJ_MINOR,CBN_CRW_INJ_SERIOUS,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
count,0.0,1.0,64.000000,6.000000,1.0,8.000000,0.0,0.0,0.0,0.0,...,17.000000,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
mean,NaN,91.0,1.218750,1.333333,3.0,1.500000,NaN,NaN,NaN,NaN,...,1.823529,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
std,NaN,NaN,0.700765,0.516398,NaN,0.534522,NaN,NaN,NaN,NaN,...,1.236694,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
25%,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
50%,NaN,91.0,1.000000,1.000000,3.0,1.500000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
75%,NaN,91.0,1.000000,1.750000,3.0,2.000000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
max,NaN,91.0,6.000000,2.000000,3.0,2.000000,NaN,NaN,NaN,NaN,...,6.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0

In [18]:
ACFT_MAKE_NAME = data_df['ACFT_MAKE_NAME']
LOC_STATE_NAME = data_df['LOC_STATE_NAME']
ACFT_MODEL_NAME = data_df['ACFT_MODEL_NAME']
RMK_TEXT = data_df['RMK_TEXT']
FLT_PHASE = data_df['FLT_PHASE']
EVENT_TYPE_DESC = data_df['EVENT_TYPE_DESC']
FATAL_FLAG = data_df['FATAL_FLAG']
LOC_STATE_NAME.head()

0    North Carolina
1           Florida
2        New Jersey
3    North Carolina
4            Alaska
Name: LOC_STATE_NAME, dtype: object

In [42]:
selected_data = pd.DataFrame([ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG]).T
# selected_data = pd.DataFrame(ACFT_MAKE_NAME,LOC_STATE_NAME)
# selected_data = pd.DataFrame(ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG)
selected_data

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN
...,...,...,...,...,...,...,...
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,NaN
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

In [49]:
ORG_data_df = selected_data.copy()

In [43]:
type(selected_data)

pandas.core.frame.DataFrame

In [44]:
selected_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   78 non-null     object
 1   LOC_STATE_NAME   83 non-null     object
 2   ACFT_MODEL_NAME  79 non-null     object
 3   RMK_TEXT         83 non-null     object
 4   FLT_PHASE        82 non-null     object
 5   EVENT_TYPE_DESC  83 non-null     object
 6   FATAL_FLAG       8 non-null      object
dtypes: object(7)
memory usage: 4.7+ KB

In [47]:
selected_data['FATAL_FLAG']

0     Yes
1     NaN
2     NaN
3     NaN
4     NaN
     ...
78    NaN
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [54]:
selected_data['FATAL_FLAG'].fillna(value='No',inplace=True)

In [56]:
selected_data['FATAL_FLAG']

0     Yes
1      No
2      No
3      No
4      No
     ...
78     No
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [57]:
selected_data.head()

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,No
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,No
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,No

In [63]:
selected_data['FATAL_FLAG'].value_counts()

No     75
Yes     8
Name: FATAL_FLAG, dtype: int64

In [84]:
selected_data['ACFT_MAKE_NAME']

0              BEECH
1               VANS
2             CESSNA
3            LANCAIR
4             CESSNA
           ...
78           AERONCA
79    NORTH AMERICAN
80          CHAMPION
81             BEECH
82            CESSNA
Name: ACFT_MAKE_NAME, Length: 83, dtype: object

In [101]:
selected_data.dropna(axis=0,inplace=True)

In [102]:
selected_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76 entries, 0 to 82
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   76 non-null     object
 1   LOC_STATE_NAME   76 non-null     object
 2   ACFT_MODEL_NAME  76 non-null     object
 3   RMK_TEXT         76 non-null     object
 4   FLT_PHASE        76 non-null     object
 5   EVENT_TYPE_DESC  76 non-null     object
 6   FATAL_FLAG       76 non-null     object
dtypes: object(7)
memory usage: 4.8+ KB

In [103]:
selected_data['ACFT_MAKE_NAME'].value_counts()

CESSNA                 23
PIPER                  10
BEECH                   9
MOONEY                  4
CHAMPION                2
                       ..
FAIRCHILD               1
PITTS                   1
CONSOLIDATED VULTEE     1
HUGHES                  1
MAULE                   1
Name: ACFT_MAKE_NAME, Length: 29, dtype: int64

In [105]:
selected_data['ACFT_MODEL_NAME'].value_counts().shape

(52,)

## Since the number of columns cause a group function by ACFT_NAME
## are manifold therefore, the result are not good enough. In fact, we can't see 
## any group

In [119]:
grp_by_ACName = selected_data.groupby(['LOC_STATE_NAME','ACFT_MODEL_NAME','RMK_TEXT','FLT_PHASE','EVENT_TYPE_DESC','FATAL_FLAG'])['ACFT_MAKE_NAME'].apply(', '.join).reset_index()
pd.set_option('display.max_row',100)
grp_by_ACName

,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_MAKE_NAME
0,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes,CESSNA
1,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,No,CESSNA
2,Alaska,180,"AIRCRAFT ON LANDING ALONG RIVER, FLIPPED OVER,...",LANDING (LDG),Accident,No,CESSNA
3,Alaska,M4,"AIRCRAFT ON TAKEOFF STRUCK A TAXIWAY SIGN, ANC...",TAKEOFF (TOF),Incident,No,MAULE
4,Arizona,33,"AIRCRAFT ON TAKEOFF, STRUCK A BIRD, RETURNED A...",TAKEOFF (TOF),Incident,No,BEECH
5,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes,NORTH AMERICAN
6,Arizona,PA28,AIRCRAFT LANDED AND WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No,PIPER
7,Arkansas,NA265,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",LANDING (LDG),Incident,No,SABRELINER
8,Arkansas,TB9,AIRCRAFT ON TAXI WING STRUCK THE PAVEMENT AND ...,TAXI (TXI),Incident,No,SOCATA
9,California,150,"AIRCRAFT, N704SL CESSNA 150, AND N57BC AVIAT ...",STANDING (STD),Accident,No,CESSNA
10,California,2T1A,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",LANDING (LDG),Incident,No,GREAT LAKES
11,California,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, MONT...",LANDING (LDG),Incident,No,BEECH
12,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,BEECH
13,California,36,AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...,LANDING (LDG),Accident,No,BEECH
14,California,8KCAB,AIRCRAFT ON LANDING GROUND LOOPED AND GEAR COL...,LANDING (LDG),Accident,No,CHAMPION
15,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,CHAMPION
16,California,AA1,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, SALIN...",LANDING (LDG),Incident,No,GRUMMAN
17,California,BT15,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",TAXI (TXI),Incident,No,CONSOLIDATED VULTEE
18,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes,FLIGHT DESIGN
19,California,M20M,"AIRCRAFT ON LANDING GEAR COLLAPSED, NAPA, CA",LANDING (LDG),Incident,No,MOONEY
20,California,RX8,"N3647A AEROSTAR INTERNATIONAL RX8 BALLOON, ON ...",LANDING (LDG),Accident,No,AEROSTAR INTERNATIONAL
21,California,S2,"AIRCRAFT, N704SL CESSNA 150, AND N57BC AVIAT ...",UNKNOWN (UNK),Accident,No,PITTS
22,California,T34,AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...,TAKEOFF (TOF),Incident,No,BEECH
23,California,TB21,"AIRCRAFT ON LANDING THE GEAR COLLAPSED, PETALU...",LANDING (LDG),Incident,No,SOCATA
24,Colorado,210,"AIRCRAFT LANDED GEAR UP, DURANGO, CO",LANDING (LDG),Incident,No,CESSNA
25,Colorado,GC1B,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",LANDING (LDG),Incident,No,GLOBE
26,Florida,152,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR PEMBR...",LANDING (LDG),Incident,No,CESSNA
27,Florida,172,"AIRCRAFT ON LANDING STRUCK A RUNWAY LIGHT, DAY...",TAXI (TXI),Incident,No,CESSNA
28,Florida,210,"AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...",LANDING (LDG),Incident,No,CESSNA
29,Florida,340,N341AG SILVER AIRWAYS FLIGHT SIL70 SAAB 340B A...,STANDING (STD),Incident,No,SAAB
30,Florida,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLASPED, CRYS...",LANDING (LDG),Incident,No,BEECH
31,Florida,55,"AIRCRAFT ON TAXI, GEAR COLLAPSED, WEST PALM BE...",TAXI (TXI),Incident,No,BEECH
32,Florida,747,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,TAKEOFF (TOF),Incident,No,BOEING
33,Florida,PA24,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",LANDING (LDG),Incident,No,PIPER
34,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes,PIPER
35,Florida,PA28,"AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...",TAKEOFF (TOF),Incident,No,PIPER
36,Florida,PA34,"HK4699G COLUMBIA REGISTRATION, PIPER PA34 AIRC...",LANDING (LDG),Incident,No,PIPER
37,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No,VANS
38,Georgia,310,"AIRCRAFT ON LANDING, GEAR COLLAPSED, GRIFFIN, GA",LANDING (LDG),Incident,No,CESSNA
39,Hawaii,206,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,UNKNOWN (UNK),Accident,No,BELL
40,Kansas,IV,"AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...",UNKNOWN (UNK),Incident,No,LANCAIR
41,Kansas,PA24,"AIRCRAFT LANDED GEAR UP, EUREKA, KS",LANDING (LDG),Incident,No,PIPER
42,Louisiana,210,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, LAKEF...",LANDING (LDG),Incident,No,CESSNA
43,Louisiana,EAGLE II,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,TAKEOFF (TOF),Accident,No,CHRISTEN
44,Maryland,M20E,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No,MOONEY
45,Maryland,M20K,"AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...",LANDING (LDG),Incident,No,MOONEY
46,Massachusetts,ERJ190,N273JB JETBLUE FLIGHT JBU891 EMBRAER ERJ190 AI...,STANDING (STD),Incident,No,EMBRAER
47,Michigan,737,AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...,TAXI (TXI),Incident,No,BOEING
48,Minnesota,A319,AMERICAN AIRLINES FLIGHT AAL476 AIRBUS A319 AI...,UNKNOWN (UNK),Accident,No,AIRBUS
49,Missouri,PA34,"AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...",LANDING (LDG),Incident,No,PIPER
50,Montana,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED AND STRUCK...",LANDING (LDG),Accident,No,CESSNA
51,Nevada,47G,N1181W BELL 47G ROTORCRAFT LANDED OFF THE RUNW...,LANDING (LDG),Accident,No,BELL
52,New Hampshire,560,N70TH DELTA PRIVATE JET FLIGHT DPJ70 CESSNA C5...,TAXI (TXI),Incident,No,CESSNA
53,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,No,CESSNA
54,New York,152,"AIRCRAFT LANDED, STRUCK A SNOWBANK AND CAUGHT ...",LANDING (LDG),Accident,No,CESSNA
55,New York,310,"AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY",LANDING (LDG),Incident,No,CESSNA
56,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,No,LANCAIR
57,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes,BEECH
58,Ohio,M20K,"AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH",LANDING (LDG),Incident,No,MOONEY
59,Oklahoma,36,"AIRCRAFT LANDED GEAR UP, TULSA, OK",LANDING (LDG),Incident,No,BEECH
60,Oregon,140,"AIRCRAFT ON LANDING, GEAR COLLAPSED AND GROUND...",LANDING (LDG),Accident,No,CESSNA
61,Oregon,175,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Accident,No,CESSNA
62,Oregon,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED, EUGENE, OR",LANDING (LDG),Incident,No,CESSNA
63,Pennsylvania,PA34,"AIRCRAFT ON APPROACH TO LAND, STRUCK TREES, LA...",APPROACH (APR),Accident,No,PIPER
64,Rhode Island,PA31,"AIRCRAFT ON LANDING STRUCK A BIRD, MIDDLETOWN, RI",LANDING (LDG),Incident,No,PIPER
65,South Dakota,150,"AIRCRAFT ON TAXI, PROP STRUCK THE GROUND, STUR...",TAXI (TXI),Accident,No,CESSNA
66,Tennessee,PA20,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...",LANDING (LDG),Incident,No,PIPER
67,Texas,150,"AIRCRAFT ON LANDING WENT OFF THE RUNWAY, THROU...",LANDING (LDG),Incident,No,CESSNA
68,Texas,182,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,No,CESSNA
69,Texas,210,AIRCRAFT FORCE LANDED IN A FIELD 2 MILES FROM ...,UNKNOWN (UNK),Accident,No,CESSNA
70,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,No,AERONCA
71,Texas,PT19,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, WES...",TAXI (TXI),Incident,No,FAIRCHILD
72,Virginia,172,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Incident,No,CESSNA
73,Virginia,500,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",TAXI (TXI),Incident,No,AERO COMMANDER
74,Virginia,GULFSTREAM200,"AIRCRAFT ON TAXI COLLIDED WITH A VEHICLE, WASH...",TAXI (TXI),Incident,No,GULFSTREAM
75,West Virginia,369,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,LANDING (LDG),Incident,No,HUGHES

### To show a better performance of 'groupby' function we reduced the number of columns
### as it can be seen it is grouped now!!!

In [121]:
grp_by_ACName1 = selected_data.groupby(['LOC_STATE_NAME','FATAL_FLAG'])['ACFT_MAKE_NAME'].apply(', '.join).reset_index()
grp_by_ACName1

,LOC_STATE_NAME,FATAL_FLAG,ACFT_MAKE_NAME
0,Alabama,Yes,CESSNA
1,Alaska,No,"CESSNA, MAULE, CESSNA"
2,Arizona,No,"PIPER, BEECH"
3,Arizona,Yes,NORTH AMERICAN
4,Arkansas,No,"SOCATA, SABRELINER"
5,California,No,"BEECH, GREAT LAKES, CONSOLIDATED VULTEE, MOONE..."
6,California,Yes,"FLIGHT DESIGN, CHAMPION, BEECH"
7,Colorado,No,"GLOBE, CESSNA"
8,Florida,No,"VANS, PIPER, CESSNA, BOEING, CESSNA, PIPER, CE..."
9,Florida,Yes,PIPER
10,Georgia,No,CESSNA
11,Hawaii,No,BELL
12,Kansas,No,"LANCAIR, PIPER"
13,Louisiana,No,"CESSNA, CHRISTEN"
14,Maryland,No,"MOONEY, MOONEY"
15,Massachusetts,No,EMBRAER
16,Michigan,No,BOEING
17,Minnesota,No,AIRBUS
18,Missouri,No,PIPER
19,Montana,No,CESSNA
20,Nevada,No,BELL
21,New Hampshire,No,CESSNA
22,New Jersey,No,CESSNA
23,New York,No,"CESSNA, CESSNA"
24,North Carolina,No,LANCAIR
25,North Carolina,Yes,BEECH
26,Ohio,No,MOONEY
27,Oklahoma,No,BEECH
28,Oregon,No,"CESSNA, CESSNA, CESSNA"
29,Pennsylvania,No,PIPER
30,Rhode Island,No,PIPER
31,South Dakota,No,CESSNA
32,Tennessee,No,PIPER
33,Texas,No,"CESSNA, CESSNA, FAIRCHILD, CESSNA, AERONCA"
34,Virginia,No,"CESSNA, GULFSTREAM, AERO COMMANDER"
35,West Virginia,No,HUGHES

In [120]:
selected_data['FATAL_FLAG'].value_counts()

No     69
Yes     7
Name: FATAL_FLAG, dtype: int64